services:
  # Database for Librebooking
  db:
    image: mariadb:latest
    restart: always
    volumes: 
     - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MARIADB_DATABASE: librebooking
      MARIADB_USER: lb_user
      MARIADB_PASSWORD: ${LB_DBUSER_PWD}
      TZ: Europe/Stockholm

  # Database management reachable through tailscale
  adminer:
    image: adminer
    restart: always
    network_mode: "service:tailscale"
    depends_on:
      - tailscale
      - db
    # ports:
    #   - 8002:8080

  # Booking service
  librebooking:
    image: caselabbet/librebooking:latest
    restart: always
    depends_on:
      - db
    networks:
      - traefik_proxy
      - default
    environment:
      - LB_DATABASE_PASSWORD=${LB_DBUSER_PWD}
      - LB_DATABASE_HOSTSPEC=db
      - LB_INSTALL_PASSWORD=${LB_INSTALL_PWD}
      - LB_DEFAULT_TIMEZONE=Europe/Stockholm

      - LB_PHPMAILER_MAILER=smtp
      - LB_PHPMAILER_SMTP_HOST=smtp.gmail.com
      - LB_PHPMAILER_SMTP_PORT=587
      - LB_PHPMAILER_SMTP_SECURE=tls
      - LB_PHPMAILER_SMTP_USERNAME=${LB_SMTP_USERNAME}
      - LB_PHPMAILER_SMTP_PASSWORD=${LB_SMTP_PASSWORD}

      - LB_EMAIL_DEFAULT_FROM_ADDRESS=booking@caselabbet.se
      - LB_EMAIL_DEFAULT_FROM_NAME=CASE Booking

      - LB_APP_TITLE=CASE LAB Booking
      - LB_ADMIN_EMAIL=booking@caselabbet.se
      - LB_ADMIN_EMAIL_NAME=CASE Booking
      - LB_COMPANY_NAME=CASE Lab
      - LB_COMPANY_URL=https://caselabbet.se
      - LB_DEFAULT_LANGUAGE=en_gb
      - LB_SCRIPT_URL=https://booked.caselabbet.se/Web

      - LB_SCHEDULE_SHOW_WEEK_NUMBERS=true
      - LB_SCHEDULE_SHOW_INACCESSIBLE_RESOURCES=false
      - LB_SCHEDULE_RESERVATION_LABEL='{title} [{name}]'
      - LB_RESERVATION_PREVENT_PARTICIPATION=true
      - LB_RESERVATION_PREVENT_RECURRENCE=true
      - LB_RESERVATION_START_TIME_CONSTRAINT=current
      - LB_RESERVATION_CHECKIN_MINUTES_PRIOR=30

      - LB_SECURITY_HEADERS=true
      - LB_REGISTRATION_REQUIRE_EMAIL_ACTIVATION=true
      - LB_CLEANUP_YEARS_OLD_DATA=999
      - LB_AUTHENTICATION_REQUIRED_EMAIL_DOMAINS=student.chalmers.se,chalmers.se
    labels:
      traefik.enable: true
      traefik.http.routers.case_booking.rule: Host(`booked.caselabbet.se`) || Host(`www.booked.caselabbet.se`)
      traefik.http.routers.case_booking.entrypoints: websecure
      traefik.http.routers.case_booking.tls.certresolver: letsencrypt
      traefik.http.services.case_booking.loadbalancer.server.port: 8080
      traefik.docker.network: traefik_proxy

  caselabbetse:
    image: caselabbet/caselabbetse:latest
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - inventory:/var/www/inventory
    labels:
      traefik.enable: true
      traefik.http.routers.case_site.rule: Host(`caselabbet.se`) || Host(`www.caselabbet.se`)
      traefik.http.routers.case_site.entrypoints: websecure
      traefik.http.routers.case_site.tls.certresolver: letsencrypt
      traefik.http.services.case_site.loadbalancer.server.port: 8080
      traefik.docker.network: traefik_proxy

  # Tunnel in for management
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-state:/var/lib/tailscale
    cap_add:
      - net_admin
      - net_raw
    restart: always

  # Inventory management, puts components.json in the webserver
  inventory:
    image: caselabbet/inventory:latest
    volumes:
      - inventory:/app/data_out
    environment:
      - ZETTLE_APIKEY=${ZETTLE_APIKEY}
    restart: always



volumes:
  db_data:
  lb_config:
  caddy_data:
  caddy_config:
  inventory:

networks:
  traefik_proxy:
    external: true
