services:
  # Database for Librebooking
  db:
    image: mariadb:latest
    restart: always
    volumes: 
     - db_data:/config
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MARIADB_DATABASE: librebooking
      MARIADB_USER: lb_user
      MARIADB_PASSWORD: ${LB_DBUSER_PWD}
      TZ: Europe/Stockholm

  # Database management reachable through tailscale
  adminer:
    image: adminer
    restart: always
    network_mode: "service:tailscale"
    depends_on:
      - tailscale
      - db
    # ports:
    #   - 8002:8080

  # Booking service
  librebooking:
    image: caselabbet/librebooking:latest
    restart: always
    depends_on:
      - db
    networks:
      - traefik_proxy
      - default
    volumes:
      - lb_config:/config
    environment:
      - LB_DATABASE_NAME=librebooking
      - LB_DATABASE_USER=lb_user
      - LB_DATABASE_PASSWORD=${LB_DBUSER_PWD}
      - LB_DATABASE_HOSTSPEC=db
      - LB_INSTALL_PASSWORD=${LB_INSTALL_PWD}
      - LB_DEFAULT_TIMEZONE=Europe/Stockholm
    labels:
      traefik.enable: true
      traefik.http.routers.case_booking.rule: Host(`staging2.caselabbet.se`)
      traefik.http.routers.case_booking.entrypoints: websecure
      traefik.http.routers.case_booking.tls.certresolver: letsencrypt
      traefik.http.services.case_booking.loadbalancer.server.port: 8080
      traefik.docker.network: traefik_proxy

  caselabbetse:
    image: caselabbet/caselabbetse:latest
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.case_site.rule: Host(`staging1.caselabbet.se`)
      traefik.http.routers.case_site.entrypoints: websecure
      traefik.http.routers.case_site.tls.certresolver: letsencrypt
      traefik.http.services.case_site.loadbalancer.server.port: 8080
      traefik.docker.network: traefik_proxy

  # Tunnel in for management
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-state:/var/lib/tailscale
    cap_add:
      - net_admin
      - net_raw
    restart: always



volumes:
  db_data:
  lb_config:
  caddy_data:
  caddy_config:

networks:
  traefik_proxy:
    external: true
