<?php

// LibreBooking configuration file edited at 2026-06-04T19:07:23+02:00

return [
    'settings' => [
        'app.title' => 'CASE LAB Booking',
        'app.debug' => false,
        'admin.email' => 'booking@caselabbet.se',
        'admin.email.name' => 'CASE Booking',
        'company.name' => 'CASE LAB',
        'company.url' => 'https://caselabbet.se',
        'default.timezone' => 'Europe/London',
        'default.language' => 'en_gb',
        'enabled.languages' => '',
        'script.url' => 'https://booked.caselabbet.se/Web',
        'install.password' => '',
        'cache.templates' => true,
        'use.local.js.libs' => true,
        'inactivity.timeout' => 30,
        'home.url' => '',
        'logout.url' => '',
        'default.homepage' => 1,
        'default.page.size' => 50,
        'css.extension.file' => '',
        'css.theme' => 'default',
        'name.format' => '{first} {last}',
        'google.analytics.tracking.id' => '',
        'slack.token' => '',
        'pages' => [
            'configuration.enabled' => true,
        ],
        'database' => [
            'type' => 'mysql',
            'hostspec' => '127.0.0.1',
            'name' => 'librebooking',
            'user' => 'lb_user',
            'password' => 'password',
        ],
        'phpmailer' => [
            'mailer' => 'smtp',
            'smtp.host' => '',
            'smtp.port' => 25,
            'smtp.secure' => '',
            'smtp.autotls' => true,
            'smtp.auth' => true,
            'smtp.username' => '',
            'smtp.password' => '',
            'sendmail.path' => '/usr/sbin/sendmail',
            'smtp.debug' => false,
        ],
        'email' => [
            'enabled' => true,
            'enforce.custom.template' => false,
            'default.from.address' => '',
            'default.from.name' => '',
        ],
        'logging' => [
            'folder' => '/var/log/librebooking/log',
            'level' => 'error',
            'sql' => false,
        ],
        'uploads' => [
            'image.upload.directory' => 'Web/uploads/images',
            'image.upload.url' => 'uploads/images',
            'reservation.attachments.enabled' => false,
            'reservation.attachment.path' => 'uploads/reservation',
            'reservation.attachment.extensions' => 'csv,doc,docx,gif,jpeg,jpg,pdf,png,ppt,pptx,txt,xls,xlsx',
        ],
        'reservation.notify' => [
            'application.admin.add' => false,
            'application.admin.update' => false,
            'application.admin.delete' => false,
            'application.admin.approval' => false,
            'group.admin.add' => false,
            'group.admin.update' => false,
            'group.admin.delete' => false,
            'group.admin.approval' => false,
            'resource.admin.add' => false,
            'resource.admin.update' => false,
            'resource.admin.delete' => false,
            'resource.admin.approval' => false,
        ],
        'schedule' => [
            'auto.scroll.today' => true,
            'show.week.numbers' => true,
            'hide.blocked.periods' => false,
            'show.inaccessible.resources' => false,
            'reservation.label' => '{title} [{name}]',
            'use.per.user.colors' => false,
            'update.highlight.minutes' => 0,
            'fast.reservation.load' => false,
            'load.mobile.views' => true,
        ],
        'reservation' => [
            'prevent.participation' => true,
            'prevent.recurrence' => true,
            'allow.guest.participation' => false,
            'allow.wait.list' => false,
            'start.time.constraint' => 'current',
            'updates.require.approval' => false,
            'title.required' => false,
            'description.required' => false,
            'checkin.minutes.prior' => 30,
            'checkin.admin.only' => false,
            'checkout.admin.only' => false,
            'reminders.enabled' => false,
            'default.start.reminder' => '',
            'default.end.reminder' => '',
        ],
        'reservation.labels' => [
            'ics.summary' => '{title}',
            'ics.my.summary' => '{title}',
            'rss.description' => '<div><span>Start</span> {startdate}</div><div><span>End</span> {enddate}</div><div><span>Organizer</span> {name}</div><div><span>Description</span> {description}</div>',
            'my.calendar' => '{resourcename} {title}',
            'resource.calendar' => '{name}',
            'reservation.popup' => '',
        ],
        'reports' => [
            'allow.all.users' => false,
        ],
        'registration' => [
            'allow.self.registration' => true,
            'require.phone' => false,
            'require.position' => false,
            'require.organization' => false,
            'hide.phone' => false,
            'hide.position' => false,
            'hide.organization' => false,
            'captcha.enabled' => true,
            'require.email.activation' => true,
            'auto.subscribe.email' => false,
            'notify.admin' => false,
        ],
        'resource' => [
            'contact.is.user' => false,
        ],
        'tablet.view' => [
            'allow.reservations' => true,
            'allow.guest.reservations' => false,
            'auto.suggest.emails' => false,
        ],
        'ics' => [
            'subscription.key' => '',
            'future.days' => 30,
            'past.days' => 0,
        ],
        'cleanup' => [
            'years.old.data' => 999,
            'delete.old.announcements' => false,
            'delete.old.blackouts' => false,
            'delete.old.reservations' => false,
        ],
        'password' => [
            'disable.reset' => false,
            'minimum.letters' => 6,
            'minimum.numbers' => 0,
            'upper.and.lower' => false,
        ],
        'privacy' => [
            'view.schedules' => true,
            'view.reservations' => false,
            'hide.user.details' => false,
            'hide.reservation.details' => false,
            'allow.guest.reservations' => false,
            'public.future.days' => 30,
        ],
        'recaptcha' => [
            'enabled' => false,
            'public.key' => '',
            'private.key' => '',
            'request.method' => 'curl',
        ],
        'security' => [
            'headers' => true,
            'strict-transport' => 'max-age=31536000',
            'x-frame' => 'deny',
            'x-content-type' => 'nosniff',
            'content-security-policy' => '',
        ],
        'credits' => [
            'enabled' => false,
            'allow.purchase' => false,
        ],
        'authentication' => [
            'hide.login.prompt' => false,
            'captcha.on.login' => false,
            'required.email.domains' => 'student.chalmers.se,chalmers.se',
            'google.login.enabled' => false,
            'google.client.id' => '',
            'google.client.secret' => '',
            'google.redirect.uri' => '/Web/google-auth.php',
            'microsoft.login.enabled' => false,
            'microsoft.client.id' => '',
            'microsoft.tenant.id' => 'common',
            'microsoft.client.secret' => '',
            'microsoft.redirect.uri' => '/Web/microsoft-auth.php',
            'facebook.login.enabled' => false,
            'facebook.client.id' => '',
            'facebook.client.secret' => '',
            'facebook.redirect.uri' => '/Web/facebook-auth.php',
            'keycloak.login.enabled' => false,
            'keycloak.url' => '',
            'keycloak.realm' => '',
            'keycloak.client.id' => '',
            'keycloak.client.secret' => '',
            'keycloak.client.uri' => '/Web/keycloak-auth.php',
            'oauth2.login.enabled' => false,
            'oauth2.name' => 'OAuth2',
            'oauth2.strip.trailing.slash' => true,
            'oauth2.url.authorize' => '',
            'oauth2.url.token' => '',
            'oauth2.url.userinfo' => '',
            'oauth2.client.id' => '',
            'oauth2.client.secret' => '',
            'oauth2.client.uri' => '/Web/oauth2-auth.php',
        ],
        'plugins' => [
            'authentication' => '',
            'authorization' => '',
            'export' => '',
            'permission' => '',
            'postregistration' => '',
            'prereservation' => '',
            'postreservation' => '',
            'styling' => '',
        ],
        'api' => [
            'enabled' => false,
            'registration.allow.self' => false,
            'authentication.group' => '',
            'accessories.ro.group' => '',
            'accounts.ro.group' => '',
            'accounts.rw.group' => '',
            'attributes.ro.group' => '',
            'groups.ro.group' => '',
            'reservations.ro.group' => '',
            'reservations.rw.group' => '',
            'resources.ro.group' => '',
            'schedules.ro.group' => '',
            'users.ro.group' => '',
        ],
    ],
];
