FROM librebooking/librebooking:5.0.3
COPY config.php /config/config.php
COPY style.css /var/www/html/Web/css/custom-style.css
COPY favicon.png /var/www/html/Web/custom-favicon.png
COPY logo.png /var/www/html/Web/img/custom-logo.png
